class Recipe {
  String label;
  String imageUrl;

  int servings;
  List<Ingredient> ingredients;

  Recipe(this.label, this.imageUrl, this.servings, this.ingredients);

  static List<Recipe> samples = [
    Recipe('Bakso', 'bakso.jpg', 4, [
      Ingredient(1, 'kg', 'daging sapi giling'),
      Ingredient(200, 'g', 'tepung tapioka'),
      Ingredient(2, 'butir', 'telur'),
      Ingredient(3, 'siung', 'bawang putih, haluskan'),
      Ingredient(2, 'sendok makan', 'kecap manis'),
      Ingredient(1, 'sendok makan', 'garam'),
      Ingredient(1, 'sendok teh', 'merica bubuk'),
      Ingredient(1, 'sendok teh', 'kaldu bubuk'),
      Ingredient(1, 'liter', 'kaldu sapi'),
      Ingredient(200, 'g', 'es batu'),
      Ingredient(0.5, 'biji', 'cabai rawit, iris tipis (opsional)'),
      Ingredient(2, 'batang', 'seledri, iris halus'),
      Ingredient(2, 'sendok makan', 'minyak goreng')
    ]),
    Recipe('Sate', 'sate.jpg', 2, [
      Ingredient(500, 'gram', 'daging ayam/daging sapi'),
      Ingredient(1, 'botol', 'kecap manis'),
      Ingredient(2, 'siung', 'bawang putih, haluskan'),
      Ingredient(1, 'sdt', 'merica bubuk'),
      Ingredient(1, 'sdt', 'garam'),
      Ingredient(1, 'sdt', 'gula pasir'),
      Ingredient(2, 'sdm', 'minyak untuk menumis'),
      Ingredient(100, 'ml', 'air'),
      Ingredient(15, 'batang', 'tusuk sate, rendam dalam air'),
      Ingredient(1, 'buah', 'jeruk nipis, ambil airnya'),
    ]),
    Recipe('Gado-Gado', 'gado.jpg', 1, [
      Ingredient(200, 'gram', 'Tahu'),
      Ingredient(200, 'gram', 'Tempe'),
      Ingredient(150, 'gram', 'Kacang Panjang'),
      Ingredient(150, 'gram', 'Kol'),
      Ingredient(100, 'gram', 'Kacang Tanah, Sangrai'),
      Ingredient(2, 'buah', 'Kentang'),
      Ingredient(2, 'buah', 'Telur Rebus'),
      Ingredient(2, 'buah', 'Ketimun'),
      Ingredient(1, 'buah', 'Tomat'),
      Ingredient(1, 'buah', 'Timun'),
      Ingredient(1, 'buah', 'Cabe Rawit (opsional)'),
      Ingredient(1, 'buah', 'Lembing'),
      Ingredient(1, 'buah', 'Tauge'),
      Ingredient(1, 'buah', 'Daun Selada'),
      Ingredient(1, 'buah', 'Daun Kol'),
    ]),
    Recipe('Pecel', 'pecel.jpg', 24, [
      Ingredient(1, 'cangkir', 'kacang tanah, sangrai'),
      Ingredient(3, 'buah', 'cabai rawit'),
      Ingredient(2, 'siung', 'bawang putih'),
      Ingredient(1, 'sendok teh', 'gula merah, sisir'),
      Ingredient(1 / 2, 'sendok teh', 'garam'),
      Ingredient(1, 'sendok makan', 'air asam jawa'),
      Ingredient(1 / 2, 'sendok teh', 'terasi, bakar'),
      Ingredient(1 / 2, 'cangkir', 'air'),
    ]),
    Recipe('Pecel Lele', 'lele.jpg', 1, [
      Ingredient(2, '1 ekor', 'lele fillet'),
      Ingredient(1, 'gelas', 'tepung beras'),
      Ingredient(1 / 2, 'gelas', 'tepung terigu'),
      Ingredient(1 / 2, 'gelas', 'tepung tapioka'),
      Ingredient(1 / 2, 'sendok teh', 'merica bubuk'),
      Ingredient(1 / 2, 'sendok teh', 'bubuk ketumbar'),
      Ingredient(1 / 2, 'sendok teh', 'garam'),
      Ingredient(1 / 2, 'sendok teh', 'baking powder'),
      Ingredient(1 / 2, 'gelas', 'air es'),
      Ingredient(2, 'gelas', 'minyak untuk menggoreng'),
    ]),
    Recipe('Soto', 'soto.jpg', 4, [
      Ingredient(500, 'gram', 'ayam'),
      Ingredient(2, 'batang', 'serai'),
      Ingredient(3, 'lembar', 'daun jeruk'),
      Ingredient(2, 'buah', 'tomat'),
      Ingredient(2, 'sendok makan', 'minyak goreng'),
      Ingredient(1, 'sendok makan', 'garam'),
      Ingredient(1, 'sendok makan', 'gula'),
      Ingredient(2, 'liter', 'air'),
      Ingredient(250, 'gram', 'tauge'),
      Ingredient(100, 'gram', 'bawang merah'),
      Ingredient(100, 'gram', 'bawang putih'),
      Ingredient(4, 'buah', 'kemiri'),
      Ingredient(1, 'sendok teh', 'ketumbar'),
      Ingredient(1, 'sendok teh', 'merica'),
      Ingredient(4, 'buah', 'cabe rawit'),
      Ingredient(4, 'buah', 'cabe merah besar'),
      Ingredient(2, 'cm', 'jahe'),
      Ingredient(2, 'cm', 'kunyit'),
      Ingredient(2, 'cm', 'lengkuas'),
      Ingredient(2, 'batang', 'daun bawang'),
      Ingredient(1, 'ikat', 'daun seledri'),
      Ingredient(200, 'gram', 'bihun'),
      Ingredient(2, 'buah', 'telur'),
      Ingredient(2, 'buah', 'jeruk nipis'),
    ]),
    Recipe('Tahu Tek', 'tahu.jpg', 4, [
      Ingredient(4, 'buah', 'tahu'),
      Ingredient(1, 'potong', 'mentimun, iris tipis'),
      Ingredient(1, 'potong', 'tauge'),
      Ingredient(1, 'potong', 'kol, parut'),
      Ingredient(1, 'potong', 'kentang rebus, iris tipis'),
      Ingredient(1, 'potong', 'bawang merah goreng'),
      Ingredient(1, 'potong', 'saus kacang'),
      Ingredient(1, 'genggaman', 'kerupuk udang'),
    ]),
    Recipe('Rawon', 'rawon.jpg', 4, [
      Ingredient(500, 'gram', 'daging sapi'),
      Ingredient(2, 'buah', 'buah keluak'),
      Ingredient(2, 'lembar', 'daun salam'),
      Ingredient(2, 'batang', 'serai, memarkan'),
      Ingredient(3, 'cm', 'lengkuas, memarkan'),
      Ingredient(4, 'buah', 'cabe rawit merah'),
      Ingredient(4, 'siung', 'bawang putih'),
      Ingredient(6, 'butir', 'bawang merah'),
      Ingredient(1, 'sendok teh', 'ketumbar bubuk'),
      Ingredient(1 / 2, 'sendok teh', 'merica bubuk'),
      Ingredient(1 / 2, 'sendok teh', 'pala bubuk'),
      Ingredient(1, 'sendok makan', 'minyak goreng'),
      Ingredient(2, 'sendok makan', 'taucu'),
      Ingredient(2, 'sendok makan', 'kecap manis'),
      Ingredient(1, 'sendok makan', 'gula merah, sisir'),
      Ingredient(1 / 2, 'sendok makan', 'garam'),
      Ingredient(1000, 'ml', 'air'),
      Ingredient(2, 'sendok makan', 'minyak untuk menumis')
    ]),
    Recipe('Rujak Cingur', 'cingur.jpg', 4, [
      Ingredient(500, 'gram', 'daging sapi'),
      Ingredient(2, 'buah', 'buah keluak'),
      Ingredient(3, 'lembar', 'daun jeruk'),
      Ingredient(2, 'batang', 'serai'),
      Ingredient(4, 'siung', 'bawang putih'),
      Ingredient(6, 'buah', 'cabe rawit'),
      Ingredient(2, 'sendok teh', 'ketumbar'),
      Ingredient(1, 'sendok teh', 'merica'),
      Ingredient(2, 'sendok teh', 'garam'),
      Ingredient(3, 'sendok makan', 'minyak goreng'),
      Ingredient(2, 'liter', 'air'),
      Ingredient(4, 'sendok makan', 'petis'),
      Ingredient(2, 'sendok makan', 'kecap manis'),
      Ingredient(4, 'buah', 'cucumber'),
      Ingredient(1, 'buah', 'jeruk nipis'),
    ]),
    Recipe('Onde-Onde', 'onde.jpg', 4, [
      Ingredient(200, 'g', 'tepung ketan'),
      Ingredient(100, 'g', 'gula merah (sisir)'),
      Ingredient(100, 'ml', 'air'),
      Ingredient(50, 'g', 'kelapa parut (untuk isi)'),
      Ingredient(1 / 2, 'sdt', 'garam'),
      Ingredient(1 / 4, 'sdt', 'vanili (opsional)'),
      Ingredient(100, 'g', 'kelapa parut (untuk taburan)'),
      Ingredient(1 / 4, 'sdt', 'garam (untuk taburan)'),
      Ingredient(1, 'lembar', 'daun pandan (untuk pewarna dan aroma)'),
      Ingredient(1, 'sdm', 'tepung terigu (untuk merekatkan)'),
      Ingredient(1, 'sdm', 'air (untuk merekatkan)'),
      Ingredient(1, 'sdm', 'wijen (untuk taburan)'),
    ]),
  ];
}

class Ingredient {
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}
